name: MVC-CAPTCHAs-Alternatives-Filters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build RandomQuestionProject
      run: dotnet build RandomQuestion/src/Filter/RandomQuestion.Filter.csproj --configuration Release --no-restore
    - name: Test RandomQuestionProject
      run: dotnet test RandomQuestion/src/Test --no-restore --verbosity normal
